markdown: kramdown
permalink: :title
timezone: America/Chicago
permalink: pretty

title: ğŸ‘¨ğŸ»â€ğŸ’» The Website of Josh Kennedy
description: Husband, father, designer, developer, all-around cheeky fellow
url: https://www.joshkennedy.me
author: Josh Kennedy
twitter:
  username: joshkennedy
  card: summary

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

include:
  - .htaccess

plugins:
  - jekyll-seo-tag
  # - jekyll-feed
  # - jekyll-webp
  # - jekyll-sitemap

exclude:
  - LICENSE
  - README
  - Rakefile
  - bower_components
  - gulpfile.babel.js
  - modernizr-config.json
  - node_modules
  - package.json
